WRITE [(igm,beus)]
WRITE [(qy,cv)]
WRITE [(zu,urdxh)]
WRITE [(cki,pq)]
WRITE [(gun,mrwdm)]
WRITE [(nl,gwds)]
WRITE [(cij,shrou)]
WRITE [(x,pnt)]
WRITE [(khw,jigq)]
WRITE [(xcopu,i)]
WRITE [(hb,on)]
WRITE [(ciiv,ff)]
WRITE [(oimnd,v)]
WRITE [(arug,nrpv)]
WRITE [(ecga,b)]
WRITE [(f,ikpf)]
WRITE [(rd,awcf)]
WRITE [(dgia,wfzso)]
WRITE [(zt,yf)]
WRITE [(yru,ttypz)]
WRITE [(bccbs,lpb)]
WRITE [(bs,dhhas)]
WRITE [(c,o)]
WRITE [(xvgr,msg)]
WRITE [(p,iut)]
WRITE [(ylu,ntlsm)]
WRITE [(lplx,d)]
WRITE [(mosg,p)]
WRITE [(uuf,vtdr)]
WRITE [(fd,up)]
WRITE [(gs,iow)]
WRITE [(dhi,isdfh)]
WRITE [(jum,j)]
WRITE [(y,alfk)]
BACKUP
BACKUP
BACKUP
BACKUP
BACKUP
BACKUP
BACKUP
BACKUP
BACKUP
BACKUP
